In [1]:
import numpy as np

In [2]:
docs = [
    'go Bangladesh',
    'Bangladesh Bangladesh',
    'hip hip hooray',
    'victory team victory',
    'long live freedom',
    'john john',
    'michael michael',
    'david david',
    'what is this',
    'long live democracy'
]

In [3]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [4]:
tokenizer.fit_on_texts(docs)

In [5]:
len(tokenizer.word_index)

16

In [6]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [2, 2, 10],
 [3, 11, 3],
 [4, 5, 12],
 [6, 6],
 [7, 7],
 [8, 8],
 [13, 14, 15],
 [4, 5, 16]]

In [10]:
from keras import Sequential
from keras.layers import Input, Dense, Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [14]:
sequences = pad_sequences(sequences, maxlen=5, padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 2,  2, 10,  0,  0],
       [ 3, 11,  3,  0,  0],
       [ 4,  5, 12,  0,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [13, 14, 15,  0,  0],
       [ 4,  5, 16,  0,  0]])

In [11]:
model = Sequential()

model.add(Embedding(17, output_dim=2, input_length=5))

model.summary()

Model: "sequential_1"


_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 2)              34        
                                                                 
Total params: 34
Trainable params: 34
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.compile('adam','accuracy')

In [15]:
pred = model.predict(sequences)
print(pred)

1/1 [==============================] - 0s 28ms/step
[[[ 0.01180123  0.00327403]
  [-0.03959643  0.04482683]
  [ 0.01679503 -0.00403055]
  [ 0.01679503 -0.00403055]
  [ 0.01679503 -0.00403055]]

 [[-0.03959643  0.04482683]
  [-0.03959643  0.04482683]
  [ 0.01679503 -0.00403055]
  [ 0.01679503 -0.00403055]
  [ 0.01679503 -0.00403055]]

 [[-0.00975349 -0.01081774]
  [-0.00975349 -0.01081774]
  [-0.02201541  0.03218938]
  [ 0.01679503 -0.00403055]
  [ 0.01679503 -0.00403055]]

 [[-0.00730761 -0.00924624]
  [ 0.03126887  0.04962537]
  [-0.00730761 -0.00924624]
  [ 0.01679503 -0.00403055]
  [ 0.01679503 -0.00403055]]

 [[ 0.01376698  0.00939604]
  [ 0.01329118 -0.04323737]
  [-0.02222651  0.04822839]
  [ 0.01679503 -0.00403055]
  [ 0.01679503 -0.00403055]]

 [[-0.01549581  0.0377943 ]
  [-0.01549581  0.0377943 ]
  [ 0.01679503 -0.00403055]
  [ 0.01679503 -0.00403055]
  [ 0.01679503 -0.00403055]]

 [[ 0.013235   -0.00369047]
  [ 0.013235   -0.00369047]
  [ 0.01679503 -0.00403055]
  [ 0.016795